### ISSUE TITLE
As an iOS developer, I can see the structure of project after create it from iOS template

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#106]
### Why

We already have the standard file organization for iOS template on wiki: https://github.com/nimblehq/ios-templates/wiki/Standard-file-organization-🗂

Please config the structure into App.xctemplates

### Acceptance Criteria

Configure file `TemplateInfo.plist` to create our structure folders

Note: A good resource to follow - https://useyourloaf.com/blog/creating-custom-xcode-project-templates/

**Comment by blyscuit** [comment]
I will start on researching this and post my finding. Will see how far can we go with it.

**Comment by suho** [comment]
@blyscuit you can implement this feature directly into the template from this pull request https://github.com/nimblehq/ios-templates/pull/104

**Comment by blyscuit** [comment]
The simplest way to this is to copy over the project structure to `Application` group resulting in:
<img width="272" alt="Screen Shot 2020-09-28 at 15 09 36" src="https://user-images.githubusercontent.com/6356137/94406840-d3827400-019c-11eb-832a-6e5e585070b6.png">
There's couple conflict with the proposed template:
1. The folders added are "Blue" folder instead of 'Yellow"
 a. Alternative is to generate these folder with a template file inside which we can have "Yellow" folder but all with file inside.
2. Editing `TemplateInfo.plist` can insert files at any level but it only possible to add file to Current Target.
 a. Will take some time to look at this.
3. There are alternative using libraries that we can specify folder structure which could be a better option as proposed by @NutanNiraula

**Comment by suho** [comment]
@blyscuit Feel free to create more subtasks for this :D

**Comment by blyscuit** [comment]
Managed to solve 1. and 2. from my earlier comments but now at the `stem` of each sun-folders, there will be a file, we can name this any file and remove it later with script. 
<img width="271" alt="Screen Shot 2020-09-28 at 16 31 30" src="https://user-images.githubusercontent.com/6356137/94415828-47764980-01a8-11eb-9792-c55f25ac2e76.png">
The other option is to keep sub-folders as "Blue" folder, this way we can have the folders be empty at start.
What do you guys think?
