### ISSUE TITLE
[RFC] Support Codemagic

### ISSUE THREAD

**Issue by phongvhd93** [nimblehq/ios-templates#304]
# Issue

There are two new projects are using CodeMagic as a CI/CD tool.And we going to have a new project from the same client; thus, it is likely to use CodeMagic as a CI/CD tool. So adding support for CodeMagic will help us speed up the CI/CD configuration a bit for future projects.
 
# Solution
- Add `codemagic.yaml` to the template as the same way we did with `bitrise.yml`.
- The template must have 3 basic workflows: `Test PR`, `Deploy Staging`, `Deploy App Store`.
- Create related documents.

# Who Benefits?
iOS Chapter and iOS developers

# What next?
 - [x] Discuss with iOS chapter members and finalize the approach.
 - [x] Create stories for the Codemagic Epic
 - [x] Implement and create pull requests. 🙌

**Comment by minhnimble** [comment]
I have the same concern with @markgravity that since there are more CI/CD options now beside Bitrise and Github Action, it might introduce redundancy setup code for a single project if we don't provide the option to choose.  It can be seen that different projects only need the CI/CD setup code on one platform only.

-> A solution for this can be enabling the ability to select the CI/CD option when running the script to setup the project. 🙏

**Comment by phongvhd93** [comment]
> I have the same concern with @markgravity that since there are more CI/CD options now beside Bitrise and Github Action, it might introduce redundancy setup code for a single project if we don't provide the option to choose. It can be seen that different projects only need the CI/CD setup code on one platform only.
> 
> -> A solution for this can be enabling the ability to select the CI/CD option when running the script to setup the project. 🙏

This can be done by scripts, after a developer selects a CI/CD service, the script will automatically remove the others. What do you think about this?

**Comment by markgravity** [comment]
@phongvhd93 sounds good to me 👍

**Comment by markgravity** [comment]
@phongvhd93 you can begin create tasks for this 👍
