### ISSUE TITLE
Minimum ios version does not match the set version when create project with template

### ISSUE THREAD

**Issue by phongvhd93** [nimblehq/ios-templates#509]
## Issue

When creating the project with `iOS-template` we have to set the minimum version for the application. However, the iOS version in the `podfile` remains `11` regardless the application's version. This causes the project to be unable to build when the iOS version applied for the app drops the support for libraries in the podfile with the older version.

![Screenshot 2023-08-04 at 10 30 55](https://github.com/nimblehq/ios-templates/assets/22606906/02472890-a4c7-4aed-9392-3b639cb02a9e)

 
## Expected

The iOS version in pod file must match the app's minimum version.
 
## Steps to reproduce

1. Create a new project with `iOS Template`
2. Set the minimum iOS version to any the input version when running the set up script.

**Comment by blyscuit** [comment]
Adding to this story, the podfile version is more related to the version of the libraries being imported than the Xcode iOS version. 
This becomes an issue when the iOS version/Swift version remove support for one of the older library. While some project might want to use the older library.
We can (and should) make the podfile version matching with the iOS version by default. I would like to point this out because some projects might want to use the older version supported libraries and are free to do so by modifying the podfile version 🙏
