### ISSUE TITLE
Add workflow to clear GitHub action cache

### ISSUE THREAD

**Issue by phongvhd93** [nimblehq/ios-templates#524]
## Why

The workflow of testing a PR has to cache the steps to cache pods and gems. Each PR will have 3 cache folders and around 20 ~ 30 MB each, and they will soon pile up when we create more and more PR. Thus, we should have a workflow to remove the cache of closed PR to free up the space on the hosting machine.

![Screenshot 2023-09-18 at 08 42 38](https://github.com/nimblehq/ios-templates/assets/22606906/dbdbf855-f4a7-4c4e-a04f-32515c79cfd4)

 
## Acceptance Criteria

- Create a workflow that will be triggered when PR get merged or closed)
- The caches related to the PR must be remove after that PR get merged or closed

## Resources
- https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

**Comment by blyscuit** [comment]
@phongvhd93 This is a very interesting find. I read further on [this](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) and it seems that 
```
When using self-hosted runners, caches from workflow runs are stored on GitHub-owned cloud storage. A customer-owned storage solution is only available with GitHub Enterprise Server.
```
So it's [nothing to worry about on the self hosted machine](https://stackoverflow.com/questions/76037402/is-caching-useful-at-all-for-self-hosted-runners). However; when using self-hosted machine, you we remove the caching completely since pods are also cached on self-hosted machine with `pod install`.

**Comment by blyscuit** [comment]
On the other hand, if the concern is with GitHub's provided storage, we do not need to worry as well because [GitHub automatically manage the storage for the users](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy).
